{% set name = "treq" %}
{% set version = "17.3.1" %}
{% set sha256 = "313af6dedecfdde2750968dc17653b6147cf2340b3479d70031cf741f5be0cf6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - incremental
  run:
    - python
    - setuptools
    - requests >=2.1.0
    - twisted >=16.4.0
    - incremental
    - six
    - attrs

test:
  imports:
    - treq

about:
  home: https://github.com/twisted/treq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python requests like API built on top of Twisted's HTTP client"
  doc_url: http://treq.readthedocs.io/
  dev_url: https://github.com/twisted/treq

extra:
  recipe-maintainers:
    - synapticarbors
