# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Wa6rr5zZh/2rhEUZrx93jgInolo/RzLa5mUplQb2HQ/91VSaV/fKZVTjmyrxLKEwvdlQXj9MYLFlv4hH0ICVCc1dG0Cvls6fuggCN1hzTngfDmwsvvphupztDgI7XGusT8SBb2kAHnPI8Xxx3HhOwgdQbTiMHf779KREry+k4gvHjSYLd+EtWbN9a4i97oxklI2HzyEIL9+qh+LOp62vmpfbCeAYIMrk1WBpq29QqJbQI3jjwpMPz785kdg9HCr5lJ7G4o6OSzaklTKdMzafc3CBCPkLZuW+Q0vKnUKh4rp91PneqP1fBxEAZw3UBUaVmH3tTgcG+6eLt1R8h8bZV8boigoGst5llNxdBmx5ynr/05ZGcsnZNE8Dcr+G8mCDfC+TjObXAfiB9nOccMzQR5afrUdToJUGixxifhcxKHd9D/VFs5RoJ1O9+eQoZy1q1j1Q9dLVQpwR9oVu9KJFPIN5tDQtVYTCmSANJBONM03OXtqKhBG1g/0+wvevdAJ4bjdRfTATU/WxQGLxpHeSMpV9804UlSF5JTiQv+VcwcJLOwhLgn+oO8FwWPvwRdcV1A+XBZsyAzVLS4L2mKUS2m3lMkQRUIJ77Okb6rLrlploApUhaLfV1wJHqqxQhL94U6UBHqzJ6I60oQ5PW3e03XRbSwu4GYAKTEx735725Ko="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
