travis:
  secure:
    BINSTAR_TOKEN: M2Q/QN20jipITAGU/mgkiekH4sg/xlK/naeA5r9A3HHoBWFiVykunX9lOpWtsLECj/JaCIfEPP0VpNkCoSVexHoyQTjFe7r2rTIffMU89ulDHfU/90uB/2ceTJ8kw49627EOFGifpsiP0IsrWyslimZxX7ut0Q+yMg7CgIKbkSSZy1WwavgbWJt+AifIyNdQL3LRI9aP3AP0Ag1PnGhRHWLdVb3sI4rGoM2IBooh2ChySgtVDR0XlUkIjovs6p2w4qy15XvBweFZ1IoMJL5vpTGiv4PjfUu6GT6pOJi+Ab8RNMUDLf0XQUYMQ5JilCujeaW0pmMFc2+aT/p9w1mkK5KNxkG3kMNPR+aJQuvsDYoRvkyRcIn0sM5zs29iDZiGC5uKI5OHoPzmjATiWvddxxVKkClPd9kUIEcrGLj4vVkiKPdJg5oS90zWF0nHHU3zFRQ8erUn8J6zK7FVD5+8+lz0hmbQqHHC1dpv4AO7TIaGUqlsVJql5geOsk6g9GlPghg6d56lFynwjxS/hvdcOzcANullgrAzfQCMKWwrbK61iMhs2CNqujL7oppQPpCAdJSedXjDJLyCSe5g/kK8X4OQjRtQ+v8fe9d14z7qqFcK7XD5QSwOfO2hK69c7Vldl/EPbGQjFGjos8jB1vXKNue2auioF5QoPrEf3grQzW8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
