travis:
  secure:
    BINSTAR_TOKEN: A7vP1IqYtegT9keE5pzc8srRzNfOVYQvtE0qrk/FVjVs5WyOcFuo7n3WMmO7/10ZtPTo8JkJhFnbajG7qDGctA7sW8JytmZb8ppiZP8u7e2cmTk+xPi007W3tuYfebcLTZTAzOpH4XFeq13zf5/fWDw/9kjYa+lMwUlmQ/cMuwaoAcWJa2LKnqbprbj9RFpqsPTg0Nag4gjdxzqCFuOa6UhRZju4fGd8J1iXZnNyGlGRWLiIWNaa0QQY3XIUsVSXEx4sCJ+LmsnJugM/df6x3s1hdKSe/3K/CMYFxlmN+v3QUuEldmaltSGovZdoLjoJOVTrjyTRHIrjNGucMM0wYl7/RNeeZKbpZY1B/faBC5yW7+ADdCRzwJ0pNuYZUSWV8CMgQOWDmZo7bb+S2wGLrJEVcaw45lb7sV6+VRjj9Ylf9bT/B2cxbaOhC3L1GAEvChW8pgsTqdosFAm5xAIT+Y6xOHriHS3m8a8Q9b86J010zxCRq+fPkHi9WbpG0bC75kuxNac8RcwOYYgaQ8bCBWKHb6SfFo5iF1av3WaNcCdIBXGc2tGkYQ9X3WMkHJr0jz8eo0jy7FbibaYtprMUe/tQqrBsUgzmtmbh+wINA2kfFdlty3iVHQsVjXaRRooSYcTEJ1mr1+DCVOV4N23FM1WENtX+wQ55fP+3yjxIp54=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
