travis:
  secure:
    BINSTAR_TOKEN: iohsWFmMf+9wowBeiYucXO4EJrP7MuYt8h8UxMk42wkzw3dMMqusQc8dtYg761y7SaMxBG6qtheco6XxvphqT+ugXsGP2+Qr8gCk8V+RJ2AhOQjnDbtXmQj4N0atQEsEC914FDSE9k8gY06oOeSjt/1ONc2+YEdJQfSx7ExocNWd82O40jJvXEv39BNHio1+sF52RXLYHN5DlKuvCGZuEURVztoD55EIrfK4idIVxknfEdUvMjt18JihBnDRemH/5ZkUWgNg/cJt44gDrlEHgCQPqWWhD3Y+jA8E0rLy6lW2059cJ9fNCKjQ/GqA2jUREaseRhLHQP1StoPTqemk/cbFIebNlLAUN5rw+wP0y+j3rrqQpEvfHmbO+K6dcYE+TxCWB6TZvZiD2sMTt0VERIxE2ZkxtBosZLSRup/eBlcsFwT1nNzDEQspt7QIbdc9l/vEmImat2l/f/ksUzEVlUzYVegUVaXpkOxKqaiGuy04GtdsTWlGrH4g+G7/0xmVzHEywObLttKt3N8K1eYd+pg5IPahhqv5RadHpYKOaZ64zYgYXJrnXj/JXHX99dELd72dotLZw6O3RdQUtTlnHe3l1yPtgmFMI4VbEyL+Ga7bg9c0cXfkCgFyegG3rOmqPiW/23Lg5czgmtlHem6L2FajV7SO3q71zY7l/zbea9A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
